### PR TITLE
Added Sign in mail feature @aveira

### PR DESCRIPTION
**Pull request by aveirahabeeb**
Added Sign in mail feature @aveira

### CODE REVIEW

**Review by HackinwaleDev — APPROVED** [review]

**Comment by HackinwaleDev** [comment]
You should have not touch the app.js and also remove the localhost from .env file. I will fix those anyways

**Comment by aveira** [comment]
> Added Sign in mail feature @aveira

Hello brother, why am I here?

**Comment by HackinwaleDev** [comment]
You did a great job bro. Just pointed that while you were done testing on the local host you forgot to revert the changes you made to the original files such as app.js and controller dir

But not to worry I have sorted those out already

**Comment by aveira** [comment]
> You did a great job bro. Just pointed that while you were done testing on the local host you forgot to revert the changes you made to the original files such as app.js and controller dir
> 
> But not to worry I have sorted those out already

brother where to check for my work?

**Pull request merged**
